package PaginaPrincipal;

import AccionEspecial.AccionBotones;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.border.Border;

public class PaginaPrincipal extends javax.swing.JFrame {
AccionBotones accionB = new AccionBotones();
  

    public PaginaPrincipal() {

        initComponents();
       
        this.setTitle("Pagina Principal");
        this.setExtendedState(6);
        this.getContentPane().setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaInicio = new javax.swing.JPanel();
        bsalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PanelCambio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cambiarPanelMenu = new javax.swing.JPanel();
        bEquipo = new PaginaPrincipal.RSButtonMetro();
        bInicio = new PaginaPrincipal.RSButtonMetro();
        bJugador = new PaginaPrincipal.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cajaInicio.setBackground(new java.awt.Color(221, 87, 76));

        bsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salida.png"))); // NOI18N
        bsalir.setContentAreaFilled(false);
        bsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEMA DE CAMPEONATO BARRIAL");

        javax.swing.GroupLayout cajaInicioLayout = new javax.swing.GroupLayout(cajaInicio);
        cajaInicio.setLayout(cajaInicioLayout);
        cajaInicioLayout.setHorizontalGroup(
            cajaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaInicioLayout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289)
                .addComponent(bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cajaInicioLayout.setVerticalGroup(
            cajaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bsalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
            .addGroup(cajaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(cajaInicio);
        cajaInicio.setBounds(0, 0, 1370, 63);

        PanelCambio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelCambioLayout = new javax.swing.GroupLayout(PanelCambio);
        PanelCambio.setLayout(PanelCambioLayout);
        PanelCambioLayout.setHorizontalGroup(
            PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambioLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(1079, Short.MAX_VALUE))
        );
        PanelCambioLayout.setVerticalGroup(
            PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(606, Short.MAX_VALUE))
        );

        getContentPane().add(PanelCambio);
        PanelCambio.setBounds(320, 70, 1173, 635);

        cambiarPanelMenu.setBackground(new java.awt.Color(204, 204, 204));

        bEquipo.setForeground(new java.awt.Color(51, 51, 51));
        bEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoEquipo.png"))); // NOI18N
        bEquipo.setText("       Equipo");
        bEquipo.setColorHover(new java.awt.Color(160, 157, 157));
        bEquipo.setColorNormal(new java.awt.Color(204, 204, 204));
        bEquipo.setColorPressed(new java.awt.Color(160, 157, 157));
        bEquipo.setColorTextHover(new java.awt.Color(51, 51, 51));
        bEquipo.setColorTextNormal(new java.awt.Color(51, 51, 51));
        bEquipo.setColorTextPressed(new java.awt.Color(51, 51, 51));
        bEquipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEquipoActionPerformed(evt);
            }
        });

        bInicio.setForeground(new java.awt.Color(51, 51, 51));
        bInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoTabla.png"))); // NOI18N
        bInicio.setText("       Inicio/Tabla de Posiciones");
        bInicio.setColorHover(new java.awt.Color(160, 157, 157));
        bInicio.setColorNormal(new java.awt.Color(204, 204, 204));
        bInicio.setColorPressed(new java.awt.Color(160, 157, 157));
        bInicio.setColorTextHover(new java.awt.Color(51, 51, 51));
        bInicio.setColorTextNormal(new java.awt.Color(51, 51, 51));
        bInicio.setColorTextPressed(new java.awt.Color(51, 51, 51));
        bInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioActionPerformed(evt);
            }
        });

        bJugador.setForeground(new java.awt.Color(51, 51, 51));
        bJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoJugador.png"))); // NOI18N
        bJugador.setText("       Jugador");
        bJugador.setColorHover(new java.awt.Color(160, 157, 157));
        bJugador.setColorNormal(new java.awt.Color(204, 204, 204));
        bJugador.setColorPressed(new java.awt.Color(160, 157, 157));
        bJugador.setColorTextHover(new java.awt.Color(51, 51, 51));
        bJugador.setColorTextNormal(new java.awt.Color(51, 51, 51));
        bJugador.setColorTextPressed(new java.awt.Color(51, 51, 51));
        bJugador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cambiarPanelMenuLayout = new javax.swing.GroupLayout(cambiarPanelMenu);
        cambiarPanelMenu.setLayout(cambiarPanelMenuLayout);
        cambiarPanelMenuLayout.setHorizontalGroup(
            cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bJugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap())
        );
        cambiarPanelMenuLayout.setVerticalGroup(
            cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarPanelMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(487, Short.MAX_VALUE))
        );

        getContentPane().add(cambiarPanelMenu);
        cambiarPanelMenu.setBounds(10, 70, 290, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bsalirActionPerformed

    private void bEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEquipoActionPerformed
    try {
        accionB.botonEquipo(PanelCambio);
    } catch (SQLException ex) {
        Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_bEquipoActionPerformed

    private void bPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPacienteActionPerformed
   
    }//GEN-LAST:event_bPacienteActionPerformed

    private void bDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDoctorActionPerformed
        
    }//GEN-LAST:event_bDoctorActionPerformed

    private void bEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnfermedadActionPerformed
       
    }//GEN-LAST:event_bEnfermedadActionPerformed

    private void bMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMedicamentoActionPerformed
       
    }//GEN-LAST:event_bMedicamentoActionPerformed

    private void bInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioActionPerformed
    try {
        accionB.botonPosiciones(PanelCambio);
    } catch (SQLException ex) {
        Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_bInicioActionPerformed

    private void bJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugadorActionPerformed
        try {
        accionB.botonJugador(PanelCambio);
    } catch (SQLException ex) {
        Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_bJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelCambio;
    private PaginaPrincipal.RSButtonMetro bEquipo;
    private PaginaPrincipal.RSButtonMetro bInicio;
    private PaginaPrincipal.RSButtonMetro bJugador;
    private javax.swing.JButton bsalir;
    private javax.swing.JPanel cajaInicio;
    private javax.swing.JPanel cambiarPanelMenu;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public class RSButtonMetro extends JButton implements MouseListener, MouseMotionListener {

        /**
         * Color para el fondo del boton
         */
        private Color colorNormal = new Color(0, 139, 139);
        private Color colorPressed = new Color(0, 0, 0);
        private Color colorHover = new Color(38, 86, 186);

        private Border bordeMoved = javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255));
        /**
         * Color para el texto
         */
        private Color colorTextNormal = new Color(255, 255, 255);
        private Color colorTextPressed = new Color(255, 255, 255);
        private Color colorTextHover = new Color(255, 255, 255);

        private Font f = new Font("Tahoma", Font.BOLD, 14);

        /**
         * Constructor de clase
         */
        @SuppressWarnings("LeakingThisInConstructor")
        public RSButtonMetro() {
            this.setFont(f);
            this.setPreferredSize(new Dimension(150, 35));
            this.setSize(new Dimension(150, 35));
            this.setBorder(null);
//        this.setBorderPainted(false);
            this.setContentAreaFilled(false);
            this.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            this.setBackground(this.colorNormal);
            this.setForeground(this.colorTextNormal);
            this.setOpaque(true);
            this.setVisible(true);
            this.addMouseListener(this);
            this.addMouseMotionListener(this);
        }

        /**
         * se pinta la imagen con dimensiones de ancho y alto iguales al alto
         * del jbutton
         */
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
        }

        public void mouseClicked(MouseEvent e) {
        }

        /**
         * Cuando se presiona el boton se cambian los colores de fondo y de
         * texto
         */
        public void mousePressed(MouseEvent e) {
            this.setForeground(this.colorTextPressed);
            this.setBackground(this.colorPressed);
        }

        /**
         * Cuando se leventa el mouse del jbutton se retoman los colores
         * originales
         */
        public void mouseReleased(MouseEvent e) {
            this.setBackground(this.colorNormal);
            this.setForeground(this.colorTextNormal);
        }

        public void mouseEntered(MouseEvent e) {
        }

        public void mouseExited(MouseEvent e) {
            this.setBorder(null);
            this.setBackground(this.colorNormal);
            this.setForeground(this.colorTextNormal);
        }

        public Color getColorPressed() {
            return colorPressed;
        }

        public void setColorPressed(Color colorPressed) {
            this.colorPressed = colorPressed;
        }

        public Color getColorTextPressed() {
            return colorTextPressed;
        }

        public void setColorTextPressed(Color colorTextPressed) {
            this.colorTextPressed = colorTextPressed;
        }

        public Color getColorHover() {
            return colorHover;
        }

        public void setColorHover(Color colorHover) {
            this.colorHover = colorHover;
        }

        public Color getColorTextHover() {
            return colorTextHover;
        }

        public void setColorTextHover(Color colorTextHover) {
            this.colorTextHover = colorTextHover;
        }

        public Color getColorNormal() {
            return colorNormal;
        }

        public void setColorNormal(Color colorNormal) {
            this.setBackground(colorNormal);
            this.colorNormal = colorNormal;
        }

        public Color getColorTextNormal() {
            return colorTextNormal;
        }

        public void setColorTextNormal(Color colorTextNormal) {
            this.setForeground(colorTextNormal);
            this.colorTextNormal = colorTextNormal;
        }

        public Border getColorBorde() {
            return bordeMoved;
        }

        public void setColorBorde(Border bordeMoved) {
            this.bordeMoved = bordeMoved;
        }

        @Override
        public void mouseDragged(MouseEvent e) {

        }

        @Override
        public void mouseMoved(MouseEvent e) {

            this.setForeground(this.colorTextHover);
            this.setBackground(this.colorHover);

            this.setBorder(bordeMoved);
        }
    }

}
